# This workflow will build the source code, authenticate with Azure and then upload the built application to a storage account

name: Deploy Static Site

on:
  workflow_run:
    workflows: ["Node.js CI"]
    types: [completed]
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    environment:
      name: Production
      url: https://milfordmenu.z35.web.core.windows.net/

    steps:
      - uses: actions/checkout@v4

      # Build the application
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
      - run: npm ci
      - run: npm run build-only

      # Upload to Azure
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Upload to blob storage
        uses: azure/cli@v2
        with:
          inlineScript: |
            az storage blob upload-batch --account-name ${{ vars.MILFORD_MENU_STORAGE_ACCOUNT_NAME }} --auth-mode key -d '$web' -s dist --overwrite true
